### ISSUE TITLE
For PUT Request User Defined Content-Type get Override with default Content-Type: application/json

### ISSUE THREAD

**Issue by mkhan004** [vlucas/frisby#319]
For PUT Request any User Defined **Content-Type** get Override with default **Content-Type: application/json**

```
"method": "PUT",
    "headers": {
      "atom-api-key": "atomqateam",
      "content-type": "application/json",
      "accept": "application/xml",
      "content-length": 70
    }
```

for this:

```
headers:
    atom-api-key: atomqateam
    Content-Type: application/xml
    Accept: application/xml
```
